services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_segura
    ports:
      - "5439:5439"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
